export const common = {
  date: document.getElementById("input_date"),
  price: document.getElementById("price_input"),
  memo: document.getElementById("memo_input"),
  payment: document.getElementById("payment_input"),
  category: document.getElementById("category_input"),
  changeButton: document.getElementById("change_btn"),
  changeImage: document.getElementById("change_button"),
  checkButton: document.getElementById("check_btn"),
  inputBar: document.querySelector(".input_bar"),
  inputBarInput: document.querySelectorAll(".input_bar input"),
  expenseCategories: [
    "생활",
    "식비",
    "교통",
    "쇼핑/뷰티",
    "의료/건강",
    "문화/여가",
    "미분류",
  ],
  incomeCategories: ["월급", "용돈", "기타수입"],
  paymentMethods: ["현찰", "체크카드", "신용카드"],
  income: "수입",
  paymentDropdownMenu: document.getElementById("payment_div"),
  categoryDropdownMenu: document.getElementById("category_div"),
  expenseSvgPath: "./src/svg/expense.svg",
  incomeSvgPath: "./src/svg/income.svg",
};
