export const common = {
  year: new Date().getFullYear(),
  month: new Date().getMonth() + 1,
  monthChar: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  yearText: document.getElementById("monthYear_text_year"),
  monthText: document.getElementById("monthYear_text_month_number"),
  monthCharText: document.getElementById("monthYear_text_month_char"),
  leftChevron: document.getElementById("chevron_left"),
  rightChevron: document.getElementById("chevron_right"),
  doc: document.getElementById("img_doc"),
  calendar: document.getElementById("img_calendar"),
  chart: document.getElementById("img_chart"),
};
